/*
 * ============================================================
 *  歌单数据文件 —— 你主要维护的就是这个文件
 * ============================================================
 *
 *  格式：每首歌一行，写成 { name: "歌名", artist: "原唱歌手" }
 *
 *  目前歌手暂时都留空 ""，之后把每个 "" 换成对应的歌手名即可。
 *
 *  注意事项：
 *  1. 花括号里的 name / artist 不要改，只改引号里的文字。
 *  2. 每一行末尾要有英文逗号「,」，最后一行可以不加。
 *  3. 歌名和歌手里如果本身有英文双引号，改成单引号避免冲突。
 */

window.SONGS = [
  // ===== 单字 / 二字 =====
  { name: "我", artist: "" },
  { name: "枫", artist: "" },
  { name: "光", artist: "" },
  { name: "空", artist: "" },
  { name: "南", artist: "" },
  { name: "火", artist: "" },
  { name: "Melody", artist: "" },
  { name: "Love uu", artist: "" },
  { name: "佳人", artist: "" },
  { name: "当你", artist: "" },
  { name: "过火", artist: "" },
  { name: "天真", artist: "" },
  { name: "晴天", artist: "" },
  { name: "过活", artist: "" },
  { name: "搁浅", artist: "" },
  { name: "心淡", artist: "" },
  { name: "退后", artist: "" },
  { name: "彩虹", artist: "" },
  { name: "轨迹", artist: "" },
  { name: "安静", artist: "" },
  { name: "假装", artist: "" },
  { name: "倒带", artist: "" },
  { name: "江南", artist: "" },
  { name: "她说", artist: "" },
  { name: "杀手", artist: "" },
  { name: "后来", artist: "" },
  { name: "即兴", artist: "" },
  { name: "冬眠", artist: "" },
  { name: "十年", artist: "" },
  { name: "爱你", artist: "" },
  { name: "走马", artist: "" },
  { name: "人质", artist: "" },
  { name: "成全", artist: "" },
  { name: "房间", artist: "" },
  { name: "天后", artist: "" },
  { name: "温柔", artist: "" },
  { name: "东西", artist: "" },
  { name: "妥协", artist: "" },
  { name: "体面", artist: "" },
  { name: "像鱼", artist: "" },
  { name: "阴天", artist: "" },
  { name: "微微", artist: "" },
  { name: "空心", artist: "" },
  { name: "离岸", artist: "" },
  { name: "丫头", artist: "" },
  { name: "信仰", artist: "" },
  { name: "嚣张", artist: "" },
  { name: "南下", artist: "" },
  { name: "演员", artist: "" },
  { name: "那年", artist: "" },
  { name: "勿忘", artist: "" },
  { name: "小宇", artist: "" },
  { name: "飞机", artist: "" },
  { name: "嘉宾", artist: "" },
  { name: "花香", artist: "" },
  { name: "红豆", artist: "" },
  { name: "大哥", artist: "" },
  { name: "宁夏", artist: "" },
  { name: "怎样", artist: "" },
  { name: "稻香", artist: "" },
  { name: "童话", artist: "" },
  { name: "倔强", artist: "" },
  { name: "白鸽", artist: "" },
  { name: "笑柄", artist: "" },
  { name: "遇见", artist: "" },
  { name: "情歌", artist: "" },
  { name: "晚安", artist: "" },
  { name: "拾墙", artist: "" },
  { name: "不如", artist: "" },
  { name: "天空", artist: "" },
  { name: "私奔", artist: "" },
  { name: "约定", artist: "" },
  { name: "心雨", artist: "" },
  { name: "洋葱", artist: "" },
  { name: "素颜", artist: "" },
  { name: "如愿", artist: "" },

  // ===== 三字 =====
  { name: "胆小鬼", artist: "" },
  { name: "有点甜", artist: "" },
  { name: "我可以", artist: "" },
  { name: "甜甜的", artist: "" },
  { name: "怎么了", artist: "" },
  { name: "都怪我", artist: "" },
  { name: "该不该", artist: "" },
  { name: "我不配", artist: "" },
  { name: "虹之间", artist: "" },
  { name: "九张机", artist: "" },
  { name: "疑心病", artist: "" },
  { name: "明明就", artist: "" },
  { name: "说爱你", artist: "" },
  { name: "日不落", artist: "" },
  { name: "静悄悄", artist: "" },
  { name: "讲真的", artist: "" },
  { name: "野孩子", artist: "" },
  { name: "红玫瑰", artist: "" },
  { name: "追光者", artist: "" },
  { name: "错的人", artist: "" },
  { name: "水星记", artist: "" },
  { name: "小幸运", artist: "" },
  { name: "小情歌", artist: "" },
  { name: "七月上", artist: "" },
  { name: "想自由", artist: "" },
  { name: "空白格", artist: "" },
  { name: "我以为", artist: "" },
  { name: "发如雪", artist: "" },
  { name: "七里香", artist: "" },
  { name: "青花瓷", artist: "" },
  { name: "安和桥", artist: "" },
  { name: "美人鱼", artist: "" },
  { name: "迷迭香", artist: "" },
  { name: "孤勇者", artist: "" },
  { name: "童话镇", artist: "" },
  { name: "离人节", artist: "" },
  { name: "达尔文", artist: "" },
  { name: "不将就", artist: "" },
  { name: "我要你", artist: "" },
  { name: "失眠酒", artist: "" },

  // ===== 四字 =====
  { name: "先生有礼", artist: "" },
  { name: "告白气球", artist: "" },
  { name: "寻水的鱼", artist: "" },
  { name: "云烟成雨", artist: "" },
  { name: "空空如也", artist: "" },
  { name: "厚颜无耻", artist: "" },
  { name: "好久不见", artist: "" },
  { name: "我怀念的", artist: "" },
  { name: "寂寞烟火", artist: "" },
  { name: "岁月神偷", artist: "" },
  { name: "忽而今夏", artist: "" },
  { name: "万有引力", artist: "" },
  { name: "猫和毛线", artist: "" },
  { name: "忽然之间", artist: "" },
  { name: "我很快乐", artist: "" },
  { name: "遥远的你", artist: "" },
  { name: "分手快乐", artist: "" },
  { name: "好不容易", artist: "" },
  { name: "一路向北", artist: "" },
  { name: "独家记忆", artist: "" },
  { name: "爱如潮水", artist: "" },
  { name: "沙漠骆驼", artist: "" },
  { name: "那么骄傲", artist: "" },
  { name: "我走以后", artist: "" },
  { name: "落日与鲸", artist: "" },
  { name: "夏天的风", artist: "" },
  { name: "没有如果", artist: "" },
  { name: "我不难过", artist: "" },
  { name: "好心分手", artist: "" },
  { name: "飞鸟和蝉", artist: "" },
  { name: "时空缝隙", artist: "" },
  { name: "错位时空", artist: "" },
  { name: "不曾相遇", artist: "" },
  { name: "路过人间", artist: "" },
  { name: "孤独患者", artist: "" },
  { name: "咖喱咖喱", artist: "" },
  { name: "词不达意", artist: "" },
  { name: "就是爱你", artist: "" },
  { name: "说好不哭", artist: "" },
  { name: "烟花易冷", artist: "" },
  { name: "说你爱我", artist: "" },
  { name: "气象站台", artist: "" },
  { name: "不再联系", artist: "" },
  { name: "一曲相思", artist: "" },
  { name: "世界末日", artist: "" },
  { name: "一笑倾城", artist: "" },
  { name: "爱的期限", artist: "" },
  { name: "心安之地", artist: "" },
  { name: "特别的人", artist: "" },
  { name: "虎口脱险", artist: "" },
  { name: "依然爱你", artist: "" },
  { name: "有何不可", artist: "" },
  { name: "不醉不会", artist: "" },

  // ===== 五字 =====
  { name: "可惜没如果", artist: "" },
  { name: "是不是爱情", artist: "" },
  { name: "后来遇见他", artist: "" },
  { name: "被驯服的象", artist: "" },
  { name: "别找我麻烦", artist: "" },
  { name: "奇妙能力歌", artist: "" },
  { name: "易燃易爆炸", artist: "" },
  { name: "爱就一个字", artist: "" },
  { name: "算什么男人", artist: "" },
  { name: "当世界倾塌", artist: "" },
  { name: "至少还有你", artist: "" },
  { name: "外面的世界", artist: "" },
  { name: "旅行的意义", artist: "" },
  { name: "突然好想你", artist: "" },
  { name: "最初的梦想", artist: "" },
  { name: "一辈子孤单", artist: "" },
  { name: "最美的期待", artist: "" },
  { name: "红色高跟鞋", artist: "" },
  { name: "银河与星斗", artist: "" },
  { name: "真的不快乐", artist: "" },
  { name: "想你这件事", artist: "" },
  { name: "好想抱住你", artist: "" },
  { name: "私奔到月球", artist: "" },

  // ===== 六字及以上 =====
  { name: "从开始到现在", artist: "" },
  { name: "我可以抱你吗", artist: "" },
  { name: "那女孩对我说", artist: "" },
  { name: "给未来的自己", artist: "" },
  { name: "不能说的秘密", artist: "" },
  { name: "阿拉斯加海湾", artist: "" },
  { name: "祝我生日快乐", artist: "" },
  { name: "说好的幸福呢", artist: "" },
  { name: "有可能的夜晚", artist: "" },
  { name: "柠檬草的味道", artist: "" },
  { name: "这条小鱼在乎", artist: "" },
  { name: "我想我不够好", artist: "" },
  { name: "如果这都不算爱", artist: "" },
  { name: "如果这就是爱情", artist: "" },
  { name: "与世界一见如故", artist: "" },
  { name: "今天也想见到你", artist: "" },
  { name: "我想我不会爱你", artist: "" },
  { name: "这世界那么多人", artist: "" },
  { name: "第57次取消发送", artist: "" },
  { name: "酒醉的探戈2001", artist: "" },
  { name: "你的酒馆对我打了烊", artist: "" },
  { name: "野狼Disco", artist: "" },
  { name: "遇到你的时候所有星星都落到我头上", artist: "" }
];
