/*
 * ============================================================
 *  歌单数据文件 —— 你主要维护的就是这个文件
 * ============================================================
 *
 *  格式：每首歌一行，写成 { name: "歌名", artist: "原唱歌手" }
 *
 *  歌手信息已按「原唱」补全（核对来源：QQ音乐 / 网易云音乐 / 酷狗音乐 + 网络资料）。
 *  合唱 / 对唱歌曲把多位歌手写在同一个 artist 里，用「、」分隔。
 *
 *  注意事项：
 *  1. 花括号里的 name / artist 不要改，只改引号里的文字。
 *  2. 每一行末尾要有英文逗号「,」，最后一行可以不加。
 *  3. 歌名和歌手里如果本身有英文双引号，改成单引号避免冲突。
 */

window.SONGS = [
  // ===== 单字 / 二字 =====
  { name: "我", artist: "蔡依林" },
  { name: "枫", artist: "周杰伦" },
  { name: "光", artist: "陈粒" },
  { name: "空", artist: "徐海俏" },
  { name: "南", artist: "Jam" },
  { name: "火", artist: "张惠妹" },
  { name: "Melody", artist: "陶喆" },
  { name: "Love uu", artist: "林俊杰" },
  { name: "佳人", artist: "鬼卞" },
  { name: "当你", artist: "王心凌" },
  { name: "过火", artist: "张信哲" },
  { name: "天真", artist: "徐良、阿悄" },
  { name: "晴天", artist: "周杰伦" },
  { name: "过活", artist: "高鱼" },
  { name: "搁浅", artist: "周杰伦" },
  { name: "心淡", artist: "容祖儿" },
  { name: "退后", artist: "周杰伦" },
  { name: "彩虹", artist: "周杰伦" },
  { name: "轨迹", artist: "周杰伦" },
  { name: "安静", artist: "周杰伦" },
  { name: "假装", artist: "蔡依林" },
  { name: "倒带", artist: "蔡依林" },
  { name: "江南", artist: "林俊杰" },
  { name: "她说", artist: "林俊杰" },
  { name: "杀手", artist: "林俊杰" },
  { name: "后来", artist: "刘若英" },
  { name: "即兴", artist: "小咪" },
  { name: "冬眠", artist: "司南" },
  { name: "十年", artist: "陈奕迅" },
  { name: "爱你", artist: "王心凌" },
  { name: "走马", artist: "陈粒" },
  { name: "人质", artist: "张惠妹" },
  { name: "成全", artist: "刘若英" },
  { name: "房间", artist: "刘瑞琦" },
  { name: "天后", artist: "陈势安" },
  { name: "温柔", artist: "五月天" },
  { name: "东西", artist: "林俊呈" },
  { name: "妥协", artist: "蔡依林" },
  { name: "体面", artist: "于文文" },
  { name: "像鱼", artist: "王贰浪" },
  { name: "阴天", artist: "莫文蔚" },
  { name: "微微", artist: "傅如乔" },
  { name: "空心", artist: "光泽" },
  { name: "离岸", artist: "苏晗" },
  { name: "丫头", artist: "王童语" },
  { name: "信仰", artist: "张信哲" },
  { name: "嚣张", artist: "en（王翊恩）" },
  { name: "南下", artist: "徐海俏" },
  { name: "演员", artist: "薛之谦" },
  { name: "那年", artist: "任然" },
  { name: "勿忘", artist: "李代沫" },
  { name: "小宇", artist: "张震岳" },
  { name: "飞机", artist: "任然" },
  { name: "嘉宾", artist: "张远" },
  { name: "花香", artist: "许绍洋" },
  { name: "红豆", artist: "王菲" },
  { name: "大哥", artist: "卫兰" },
  { name: "宁夏", artist: "梁静茹" },
  { name: "怎样", artist: "戴佩妮" },
  { name: "稻香", artist: "周杰伦" },
  { name: "童话", artist: "光良" },
  { name: "倔强", artist: "五月天" },
  { name: "白鸽", artist: "伍佰" },
  { name: "笑柄", artist: "陈小满" },
  { name: "遇见", artist: "孙燕姿" },
  { name: "情歌", artist: "梁静茹" },
  { name: "晚安", artist: "颜人中" },
  { name: "拾墙", artist: "Jam" },
  { name: "不如", artist: "秦海清" },
  { name: "天空", artist: "王菲" },
  { name: "私奔", artist: "郑钧" },
  { name: "约定", artist: "周蕙" },
  { name: "心雨", artist: "周杰伦" },
  { name: "洋葱", artist: "杨宗纬" },
  { name: "素颜", artist: "许嵩、何曼婷" },
  { name: "如愿", artist: "王菲" },

  // ===== 三字 =====
  { name: "胆小鬼", artist: "梁咏琪" },
  { name: "有点甜", artist: "汪苏泷、BY2" },
  { name: "我可以", artist: "蔡旻佑" },
  { name: "甜甜的", artist: "周杰伦" },
  { name: "怎么了", artist: "周杰伦、袁咏琳" },
  { name: "都怪我", artist: "胡66" },
  { name: "该不该", artist: "莫智钦" },
  { name: "我不配", artist: "周杰伦" },
  { name: "虹之间", artist: "金贵晟" },
  { name: "九张机", artist: "叶炫清" },
  { name: "疑心病", artist: "任然" },
  { name: "明明就", artist: "周杰伦" },
  { name: "说爱你", artist: "蔡依林" },
  { name: "日不落", artist: "蔡依林" },
  { name: "静悄悄", artist: "陈泫孝" },
  { name: "讲真的", artist: "曾惜" },
  { name: "野孩子", artist: "杨千嬅" },
  { name: "红玫瑰", artist: "陈奕迅" },
  { name: "追光者", artist: "岑宁儿" },
  { name: "错的人", artist: "萧亚轩" },
  { name: "水星记", artist: "郭顶" },
  { name: "小幸运", artist: "田馥甄" },
  { name: "小情歌", artist: "苏打绿" },
  { name: "七月上", artist: "Jam" },
  { name: "想自由", artist: "林宥嘉" },
  { name: "空白格", artist: "蔡健雅" },
  { name: "我以为", artist: "品冠" },
  { name: "发如雪", artist: "周杰伦" },
  { name: "七里香", artist: "周杰伦" },
  { name: "青花瓷", artist: "周杰伦" },
  { name: "安和桥", artist: "宋冬野" },
  { name: "美人鱼", artist: "林俊杰" },
  { name: "迷迭香", artist: "周杰伦" },
  { name: "孤勇者", artist: "陈奕迅" },
  { name: "童话镇", artist: "暗杠" },
  { name: "离人节", artist: "蔡依林" },
  { name: "达尔文", artist: "蔡健雅" },
  { name: "不将就", artist: "李荣浩" },
  { name: "我要你", artist: "任素汐" },
  { name: "失眠酒", artist: "程安" },

  // ===== 四字 =====
  { name: "先生有礼", artist: "丸子呦、国风引力" },
  { name: "告白气球", artist: "周杰伦" },
  { name: "寻水的鱼", artist: "许飞" },
  { name: "云烟成雨", artist: "房东的猫" },
  { name: "空空如也", artist: "任然" },
  { name: "厚颜无耻", artist: "曲肖冰" },
  { name: "好久不见", artist: "陈奕迅" },
  { name: "我怀念的", artist: "孙燕姿" },
  { name: "寂寞烟火", artist: "朱婧汐" },
  { name: "岁月神偷", artist: "金玟岐" },
  { name: "忽而今夏", artist: "汪苏泷" },
  { name: "万有引力", artist: "汪苏泷" },
  { name: "猫和毛线", artist: "庆庆" },
  { name: "忽然之间", artist: "莫文蔚" },
  { name: "我很快乐", artist: "刘惜君" },
  { name: "遥远的你", artist: "221小伙伴" },
  { name: "分手快乐", artist: "梁静茹" },
  { name: "好不容易", artist: "张靓颖" },
  { name: "一路向北", artist: "周杰伦" },
  { name: "独家记忆", artist: "陈小春" },
  { name: "爱如潮水", artist: "张信哲" },
  { name: "沙漠骆驼", artist: "展展与罗罗" },
  { name: "那么骄傲", artist: "金海心" },
  { name: "我走以后", artist: "张靓颖" },
  { name: "落日与鲸", artist: "天舞" },
  { name: "夏天的风", artist: "温岚" },
  { name: "没有如果", artist: "梁静茹、严爵" },
  { name: "我不难过", artist: "孙燕姿" },
  { name: "好心分手", artist: "卢巧音、王力宏" },
  { name: "飞鸟和蝉", artist: "任然" },
  { name: "时空缝隙", artist: "苏星婕" },
  { name: "错位时空", artist: "艾辰" },
  { name: "不曾相遇", artist: "亦勋" },
  { name: "路过人间", artist: "郁可唯" },
  { name: "孤独患者", artist: "陈奕迅" },
  { name: "咖喱咖喱", artist: "牛奶咖啡" },
  { name: "词不达意", artist: "林忆莲" },
  { name: "就是爱你", artist: "陶喆" },
  { name: "说好不哭", artist: "周杰伦、五月天阿信" },
  { name: "烟花易冷", artist: "周杰伦" },
  { name: "说你爱我", artist: "S.H.E" },
  { name: "气象站台", artist: "Uu（刘梦妤）" },
  { name: "不再联系", artist: "夏天Alex" },
  { name: "一曲相思", artist: "半阳" },
  { name: "世界末日", artist: "周杰伦" },
  { name: "一笑倾城", artist: "汪苏泷" },
  { name: "爱的期限", artist: "薛之谦" },
  { name: "心安之地", artist: "许嵩" },
  { name: "特别的人", artist: "方大同" },
  { name: "虎口脱险", artist: "老狼" },
  { name: "依然爱你", artist: "王力宏" },
  { name: "有何不可", artist: "许嵩" },
  { name: "不醉不会", artist: "田馥甄" },

  // ===== 五字 =====
  { name: "可惜没如果", artist: "林俊杰" },
  { name: "是不是爱情", artist: "何洁" },
  { name: "后来遇见他", artist: "胡66" },
  { name: "被驯服的象", artist: "蔡健雅" },
  { name: "别找我麻烦", artist: "蔡健雅" },
  { name: "奇妙能力歌", artist: "陈粒" },
  { name: "易燃易爆炸", artist: "陈粒" },
  { name: "爱就一个字", artist: "张信哲" },
  { name: "算什么男人", artist: "周杰伦" },
  { name: "当世界倾塌", artist: "喻昕可" },
  { name: "至少还有你", artist: "林忆莲" },
  { name: "外面的世界", artist: "齐秦" },
  { name: "旅行的意义", artist: "陈绮贞" },
  { name: "突然好想你", artist: "五月天" },
  { name: "最初的梦想", artist: "范玮琪" },
  { name: "一辈子孤单", artist: "刘若英" },
  { name: "最美的期待", artist: "周笔畅" },
  { name: "红色高跟鞋", artist: "蔡健雅" },
  { name: "银河与星斗", artist: "yihuik苡慧" },
  { name: "真的不快乐", artist: "李飘飘" },
  { name: "想你这件事", artist: "烟（许佳豪）" },
  { name: "好想抱住你", artist: "程佳佳" },
  { name: "私奔到月球", artist: "五月天、陈绮贞" },

  // ===== 六字及以上 =====
  { name: "从开始到现在", artist: "张信哲" },
  { name: "我可以抱你吗", artist: "张惠妹" },
  { name: "那女孩对我说", artist: "黄义达" },
  { name: "给未来的自己", artist: "梁静茹" },
  { name: "不能说的秘密", artist: "周杰伦" },
  { name: "阿拉斯加海湾", artist: "菲道尔" },
  { name: "祝我生日快乐", artist: "温岚" },
  { name: "说好的幸福呢", artist: "周杰伦" },
  { name: "有可能的夜晚", artist: "曾轶可" },
  { name: "柠檬草的味道", artist: "蔡依林" },
  { name: "这条小鱼在乎", artist: "王OK、洪佩瑜" },
  { name: "我想我不够好", artist: "单色凌" },
  { name: "如果这都不算爱", artist: "张学友" },
  { name: "如果这就是爱情", artist: "张靓颖" },
  { name: "与世界一见如故", artist: "王小小" },
  { name: "今天也想见到你", artist: "焦迈奇" },
  { name: "我想我不会爱你", artist: "田馥甄" },
  { name: "这世界那么多人", artist: "莫文蔚" },
  { name: "第57次取消发送", artist: "菲菲公主（陆绮菲）" },
  { name: "酒醉的探戈2001", artist: "动力火车" },
  { name: "你的酒馆对我打了烊", artist: "陈雪凝" },
  { name: "野狼Disco", artist: "宝石Gem" },
  { name: "遇到你的时候所有星星都落到我头上", artist: "高姗" }
];
